# fly.toml app configuration file generated for phone-ck on 2023-10-12T19:08:40+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "phone-ck"
primary_region = "sin"

[build]

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
